// <auto-generated />
namespace RailwayReservationMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class sign : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sign));
        
        string IMigrationMetadata.Id
        {
            get { return "202212210524059_sign"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
